// resources/_js/Pages/jobs/Index.vue
<script lang="ts" setup>

import {Job, Pagination} from "@/utils/types";
import AppLayout from "@/layouts/AppLayout.vue";
import JobPreview from "@/components/JobPreview.vue";
import Paginator from "@/components/Paginator.vue";
import _ from "lodash";
import {router} from "@inertiajs/vue3";
import {AutoCompleteCompleteEvent} from "primevue/autocomplete";
import {regions as _regions} from "@/utils/constants";
import {ref} from "vue";

defineProps<{
	jobs: Pagination<Job>
}>()

defineOptions({layout: AppLayout})

const search = ref(new URL(location.href).searchParams.get("q"));
const region = ref(new URL(location.href).searchParams.get("region"));
const regions = ref(_regions)

const searchJobs = _.throttle(() => {
	let url = "/jobs?";
	const searchParams = new URLSearchParams();
	if (search.value) searchParams.set("q", search.value);
	if (region.value) searchParams.set("region", region.value);
	router.visit(url + searchParams.toString(), {
		only: ["jobs"], preserveState: true,
	});
}, 100);

function searchRegion(event: AutoCompleteCompleteEvent) {
	regions.value = _regions.filter((region) => region.toLowerCase().includes(event.query.toLowerCase()));
}
</script>

<template>
	<div class="h-full z-0">
		<div class="space-x-5">
			<InputText
				v-model="search"
				placeholder="Search..."
				@input="searchCompanies"
			/>
			<AutoComplete
				v-model="region"
				:suggestions="regions"
				dropdown
				dropdown-class="bg-blue-500"
				placeholder="Region"
				@complete="searchRegion"
				@itemSelect="searchJobs"
			/>
		</div>
		<div class="space-y-5 mt-3">
			<JobPreview
				v-for="job in jobs.data"
				:key="job.id"
				:job="job"
			/>
		</div>
	</div>

	<Paginator :paginator="jobs"/>
</template>

// resources/js/Pages/jobs/Index.tsx
import {Job, Pagination} from "@/lib/types";
import JobPreview from "@/components/JobPreview";
import {Input} from "@/components/ui/input";
import ComboBox from "@/components/ComboBox";
import {regions as _regions} from "@/lib/constants";
import {Button} from "@/components/ui/button";
import React, {useState} from "react";
import {router} from "@inertiajs/react";
import Paginator from "@/components/Paginator";

interface Props {
	jobs: Pagination<Job>
}

export default function Index({ jobs }: Props) {
	const [regions, setRegions] = useState<string[]>(new URL(location.href).searchParams.get('region')?.split(','))
	const [search, setSearch] = useState(new URL(location.href).searchParams.get('q') ?? '')

	const handleSearch = () => {
		const searchParams = new URLSearchParams()
		if (regions.length > 0) searchParams.set('region', regions.join(','))
		if (search) searchParams.set('q', search);
		router.visit('/jobs?' + searchParams.toString(), {
			only: ['jobs'],
			preserveState: true
		})
	}
	return (
		<>
			<div className="flex items-center gap-5 mb-5">
				<Input type="text" role="search" value={search} placeholder="Search..." className="w-52" onChange={e => setSearch(e.currentTarget.value)} />
				<ComboBox value={regions} onChange={setRegions} items={_regions.map(region => ({ label: region, value: region.toLowerCase()}))} />
				<Button onClick={handleSearch}>Search</Button>
			</div>
			<div className="space-y-5">
				{jobs.data.map(job => (
					<JobPreview job={job} key={job.id} />
				))}
			</div>
			<Paginator paginator={jobs} />
		</>
	)
}
