// resources/js/components/CompanyPreview.tsx
import React from "react"
import type { Company} from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {MapPinIcon} from "@heroicons/react/24/outline";
import { Link } from '@inertiajs/react'
import route from "ziggy-js";

interface Props {
	company: Company
}

export default function CompanyPreview({ company }: Props) {
	return (
		<Card className="flex">
			<div className="shrink-0 flex items-center pl-4">
				<img src={company.logo} alt={company.name} className="w-28 aspect-square object-contain object-center" />
			</div>
			<div>
				<CardHeader className="!pb-4">
					<CardTitle className="flex items-center justify-between">
						<Link className="text-xl pb-3" href={route('companies.show', [company.id])}>
							{company.name}
						</Link>
						<div className="flex items-center gap-1">
							<MapPinIcon className="w-5 h-5 inline-block" />
							<span className="text-base font-medium">{company.location}</span>
						</div>
					</CardTitle>

					<CardDescription className="line-clamp-3">{company.description}</CardDescription>
				</CardHeader>
				<CardContent className="font-medium">
					{company.jobs_count} Jobs available
				</CardContent>
			</div>
		</Card>
	)
}

// resources/js/components/CompanyPreview.vue
<script lang="ts" setup>
import type {Company} from "@/utils/types";
import Card from "primevue/card";
import route from "ziggy-js";

defineProps<{
	company: Company;
}>();
</script>

<template>
	<Card :pt="{
		content: {
			class: '!py-0 line-clamp-3'
		},
		title: {
			class: 'flex items-center justify-between'
		}
	}">
		<template #title>
			<Link :href="route('companies.show', [company.id])" class="hover:text-blue-500">{{ company.name }}</Link>
			<div class="space-x-2">
				<i class="pi pi-map-marker"></i>
				<span class="font-medium text-base">{{ company.location }}</span>
			</div>
		</template>

		<template #content>
			{{ company.description }}
		</template>
	</Card>
</template>
