// resources/js/components/Header.tsx
import {
	NavigationMenu,
	NavigationMenuItem,
	NavigationMenuLink,
	NavigationMenuList,
	navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuSeparator,
	DropdownMenuTrigger
} from '@/components/ui/dropdown-menu'
import { UserCircleIcon } from '@heroicons/react/24/solid'
import { Link, usePage } from '@inertiajs/react'
import route from "ziggy-js";

export default function Header() {
	return (
		<header className="sticky top-0 h-16 bg-white flex items-center justify-around">
			<Link href={route('home')} className="text-2xl font-bold">JobMarket</Link>

			<NavigationMenu>
				<NavigationMenuList>
					<NavigationMenuItem>
						<NavigationMenuLink className={navigationMenuTriggerStyle()} asChild>
							<Link href={route('companies.create')}>
								Start Listing
							</Link>
						</NavigationMenuLink>
					</NavigationMenuItem>
					<NavigationMenuItem>
						<NavigationMenuLink className={navigationMenuTriggerStyle()} asChild>
							<Link href={route('jobs.index')}>
								Jobs
							</Link>
						</NavigationMenuLink>
					</NavigationMenuItem>
					<NavigationMenuItem>
						<NavigationMenuLink className={navigationMenuTriggerStyle()} asChild>
							<Link href={route('companies.index')}>
								Companies
							</Link>
						</NavigationMenuLink>
					</NavigationMenuItem>
					<NavigationMenuItem className={navigationMenuTriggerStyle()} asChild>
						{usePage().props.user ?
							(
								<DropdownMenu>
									<DropdownMenuTrigger className="flex items-center justify-center">
										<UserCircleIcon className="w-5 h-5 text-slate-800" />
									</DropdownMenuTrigger>
									<DropdownMenuContent>
										<DropdownMenuItem>
											<Link className="w-full" href={route('dashboard')}>
												Dashboard
											</Link>
										</DropdownMenuItem>
										<DropdownMenuItem>
											<Link className="w-full" href="/settings">
												Settings
											</Link>
										</DropdownMenuItem>
										<DropdownMenuSeparator />
										<DropdownMenuItem>
											<Link href={route('auth.logout')} method="post" as="button" className="w-full text-red-500 text-start">
												Logout
											</Link>
										</DropdownMenuItem>
									</DropdownMenuContent>
								</DropdownMenu>
							)
							: (
								<Link href={route('auth.login')}>Login</Link>
							)
						}

					</NavigationMenuItem>
				</NavigationMenuList>
			</NavigationMenu>
		</header>
	)
}

// resources/js/components/Header.vue
<script setup lang="ts">
	import { Link, usePage } from '@inertiajs/vue3'
    import { UserCircleIcon} from "@heroicons/vue/24/solid";
    import Dropdown from "@/components/Dropdown.vue";

    const user = usePage().props.user;

    const dropDownLinks: {name: string, link: string, class?: string}[] = [
        {
            name: 'Dashboard',
            link: '/dashboard',
        },
        {
            name: 'Settings',
            link: '/settings'
        },
        {
            name: 'Logout',
            link: '/auth/logout',
            class: 'text-red-500'
        }
    ]
</script>

<template>
	<header class="sticky top-0 left-0 flex items-center justify-around h-16 bg-white">
	<Link href="/"
	   class="text-2xl font-bold text-sky-500 tracking-tighter">JobMarket</Link>

	<nav>
		<ul class="flex items-center justify-around gap-10">
			<li>
				<Link href="/companies/create"
				   class="font-medium hover:text-sky-500 hover:underline">
					Start Listing
				</Link>
			</li>
			<li>
				<Link href="/jobs" class="font-medium hover:text-sky-500 hover:underline">
					Jobs
				</Link>
			</li>
			<li>
				<Link href="/companies" class="font-medium hover:text-sky-500 hover:underline">
					Companies
				</Link>
			</li>
		</ul>
	</nav>
    <Dropdown v-if="user" />

	<a v-else href="/auth/login" class="font-medium hover:text-sky-500 hover:underline">
		Login
	</a>
</header>
</template>

<style scoped>

</style>
