// resources/js/components/JobPreview.tsx
import React from "react"
import type { Job } from '@/lib/types'
import {Card, CardContent, CardHeader, CardTitle, CardDescription} from '@/components/ui/card'
import {ClockIcon, MapPinIcon, StarIcon} from "@heroicons/react/24/outline";
import {Link} from "@inertiajs/react";
import route from "ziggy-js";
import {convertDate} from "@/lib/utils";

interface Props {
	job: Job
}

export default function JobPreview({ job }: Props) {
	return (
		<Card>
			<CardHeader>
				<CardTitle className="flex items-center justify-between">
					<Link href={route('jobs.show', [job.id])}>
						{job.name}
					</Link>
					<span className="font-normal text-base">{convertDate(job.created_at)}</span>
				</CardTitle>
				<CardDescription className="line-clamp-2">{job.description}</CardDescription>
			</CardHeader>
			<CardContent>
				<div className="space-x-5">
					<div className="inline-flex items-center gap-2">
						<ClockIcon className="w-5 h-5" />
						<span className="capitalize">{job.employment_type}</span>
					</div>
					<div className="inline-flex items-center gap-2">
						<StarIcon className="w-5 h-5" />
						<span className="capitalize">{job.experience_level}</span>
					</div>
					<div className="inline-flex items-center gap-2">
						<MapPinIcon className="w-5 h-5" />
						<span className="capitalize">{job.location}</span>
					</div>
				</div>
			</CardContent>
		</Card>
	)
}

// resources/js/components/JobPreview.vue
<script lang="ts" setup>
import type {Job} from "@/utils/types";
import {convertDate} from "@/utils/functions";
import route from "ziggy-js";

const props = defineProps<{
	job: Job
}>()
</script>

<template>
	<Card :pt="{
		content: {
			class: '!p-1'
		},
		title: {
			class: 'flex items-center justify-between'
		},
		subtitle: { class: 'line-clamp-2' }
	}">
		<template #title>
			<Link :href="route('jobs.show', [job.id])">
				<h4 class="hover:text-blue-500">{{ job.name }}</h4>
			</Link>
			<span class="text-base font-normal">{{ convertDate(job.created_at) }}</span>
		</template>
		<template #subtitle>
			{{ job.description }}
		</template>
		<template #content>
			<div class="flex items-center justify-start gap-5">
				<div class="space-x-2">
					<i class="pi pi-clock"></i>
					<span class="capitalize">{{ job.employment_type }}</span>
				</div>
				<div class="space-x-2">
					<i class="pi pi-map-marker"></i>
					<span>{{ job.location }}</span>
				</div>
				<div class="space-x-2">
					<i class="pi pi-star"></i>
					<span class="capitalize">{{ job.experience_level }}</span>
				</div>

				<Link class="ml-auto" href="#">
					<Button class="bg-blue-500" label="Apply"/>
				</Link>
			</div>
		</template>
	</Card>
</template>
