// resources/js/components/Paginator.vue
<script lang="ts" setup>
import {Link} from '@inertiajs/vue3'
import {Pagination} from "@/utils/types";

const props = defineProps<{
	paginator: Pagination<any>
}>()
const show = props.paginator.total > props.paginator.per_page
</script>

<template>
	<div v-show="false" class="flex items-center justify-center mt-5">
		<Link
			v-for="link in paginator.links"
			:class="{
				'px-3 py-1.5 ring-1 ring-gray-300 hover:bg-blue-200 focus:bg-gray-50': true,
				'font-medium bg-blue-500 hover:bg-blue-500 text-white border-blue-500': link.active,
				'pointer-events-none bg-gray-100': link.url == null
			}"
			:href="link.url ?? '#'"
			v-html="link.label"
		/>
	</div>
</template>

// resources/js/components/Paginator.tsx
import React from "react"
import type { Pagination } from '@/lib/types'
import { Button } from "@/components/ui/button";
import { Link } from '@inertiajs/react'

interface Props {
	paginator: Pagination<any>
}

export default function Paginator({ paginator }: Props) {
	return (
		paginator.total > paginator.per_page &&
		<div className="flex items-center justify-center gap-1 my-5">
			{paginator.links.map((link, i) => (
				<Link disabled={Boolean(link.url)} href={link.url} className={link.url ? '': 'pointer-events-none'} key={i}>
					<Button variant="outline" disabled={!link.url} className={link.active ? 'text-white bg-slate-900 hover:bg-slate-800 hover:text-white': ''} dangerouslySetInnerHTML={{ __html: link.label}}/>
				</Link>
			))}
		</div>
	)
}
