// resources/js/Pages/auth/Login.tsx
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {Link, useForm} from "@inertiajs/react";
import {FormEvent} from "react";
import route from "ziggy-js";

export default function Login() {
	const form = useForm({
		email: '',
		password: '',
		remember: false
	})

	function handleSubmit(e: FormEvent<HTMLFormElement>) {
		e.preventDefault();
		form.post('/auth/login');
	}

	return (
		<>
			<div className="space-y-6 w-80">
				<div className="space-y-2 text-center">
					<h1 className="text-2xl font-semibold tracking-tight">Login</h1>
					<p className="text-sm text-muted-foreground">Enter your credentials to enter your account</p>
				</div>
				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<Label className="block mb-1" htmlFor="email">Email</Label>
						<Input value={form.data.email} onChange={e => form.setData('email', e.currentTarget.value)} id="email" placeholder="email@example.com" type="text" autoComplete="email"/>
						{form.errors.email && (
							<span className="block mt-2 text-xs text-red-500">{form.errors.email}</span>
						)}
					</div>
					<div>
						<Label className="block mb-1" htmlFor="password">Password</Label>
						<Input value={form.data.password} onChange={e => form.setData('password', e.currentTarget.value)} id="password" type="password" placeholder="*****" autoComplete="current-password"/>
						{form.errors.password && (
							<span className="block mt-2 text-xs text-red-500">{form.errors.password}</span>
						)}
					</div>
					<div className="flex items-center gap-2">
						<Checkbox id="remember" checked={form.data.remember} onCheckedChange={e => form.setData('remember', e)} />
						<Label className="text-sm font-normal" htmlFor="remember">Remember me</Label>
					</div>
					<Button type="submit" className="w-full">Login</Button>
				</form>
			</div>
			<Button variant="ghost" asChild className="absolute top-10 right-10">
				<Link href={route('auth.register')}>
					Register
				</Link>
			</Button>
		</>
	)
}

// resources/_js/Pages/auth/Login.vue
<script lang="ts" setup>
import AuthLayout from "@/layouts/AuthLayout.vue";
import { useForm } from "@inertiajs/vue3";
import route from "ziggy-js";

defineOptions({ layout: AuthLayout });

let form = useForm({
	email: null,
	password: null,
});

function handleSubmit() {
	form.post("/auth/login", {
		onError(errors) {
			if (errors.email === "Invalid Credentials") {
				form.reset("password");
			}
			//@ts-ignore
			setTimeout(() => form.clearErrors(...Object.keys(errors)), 3000);
		},
	});
}
</script>

<template>
	<form class="w-96 flex flex-col gap-5" @submit.prevent="handleSubmit">
		<h1 class="text-2xl font-semibold text-center">Login</h1>

		<label class="flex flex-col gap-2">
			<span>Email</span>
			<InputText v-model="form.email" />
			<small v-if="form.errors.email" class="text-red-500">{{
				form.errors.email
			}}</small>
		</label>

		<label class="flex flex-col gap-2">
			<span>Password</span>
			<Password
				v-model="form.password"
				:feedback="false"
				inputClass="w-full"
				toggleMask
			/>
			<small v-if="form.errors.password" class="text-red-500">{{
				form.errors.password
			}}</small>
		</label>

		<Button type="submit" class="bg-blue-500" label="Login" />

		<p class="text-sm mt-3 text-center text-gray-800">
			Not logged in yet?
			<Link
				:href="route('auth.register')"
				class="font-medium text-blue-500 hover:underline"
			>
				Register instead!
			</Link>
		</p>
	</form>
</template>
