// resources/js/Pages/companies/Index.vue
<script lang="ts" setup>
import CompanyPreview from "@/components/CompanyPreview.vue";
import Paginator from "@/components/Paginator.vue";
import { router } from "@inertiajs/vue3";
import { ref } from "vue";
import _ from "lodash";
import type { Company, Pagination } from "@/utils/types";
import AppLayout from "@/layouts/AppLayout.vue";
import { regions as _regions } from "@/utils/constants";
import { AutoCompleteCompleteEvent } from "primevue/autocomplete";

defineProps<{
	companies: Pagination<Company>;
}>();

defineOptions({ layout: AppLayout });

const search = ref(new URL(location.href).searchParams.get("q"));
const region = ref(new URL(location.href).searchParams.get("region"));
const regions = ref(_regions);

const searchCompanies = _.throttle(() => {
	let url = "/companies?";
	const searchParams = new URLSearchParams();
	if (search.value) searchParams.set("q", search.value);
	if (region.value) searchParams.set("region", region.value);
	router.visit(url + searchParams.toString(), {
		only: ["companies"],
		preserveState: true,
	});
}, 100);

function searchRegion(event: AutoCompleteCompleteEvent) {
	regions.value = _regions.filter((region) =>
		region.toLowerCase().includes(event.query.toLowerCase())
	);
}
</script>

<template>
	<div class="w-full">
		<div class="space-x-5">
			<InputText
				v-model="search"
				placeholder="Search..."
				@input="searchCompanies"
			/>
			<AutoComplete
				v-model="region"
				:suggestions="regions"
				dropdown
				dropdown-class="bg-blue-500"
				placeholder="Region"
				@complete="searchRegion"
				@itemSelect="searchCompanies"
			/>
			<Button
				class="bg-blue-500"
				label="Search"
				@click="searchCompanies"
			/>
		</div>
		<div class="space-y-5 mt-3">
			<CompanyPreview
				v-for="company in companies.data"
				:key="company.id"
				:company="company"
			/>
		</div>
		<Paginator :paginator="companies" />
	</div>
</template>

// resources/js/Pages/companies/Index.tsx
import React, {useState} from "react"
import type {Company, Pagination} from "@/lib/types";
import CompanyPreview from "@/components/CompanyPreview";
import Paginator from "@/components/Paginator";
import ComboBox from "@/components/ComboBox";
import { regions as _regions } from "@/lib/constants";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { router, usePage } from "@inertiajs/react";

interface Props {
	companies: Pagination<Company>
}

export default function Index({ companies }: Props) {
	const [regions, setRegions] = useState<string[]>(new URL(location.href).searchParams.get('region')?.split(','))
	const [search, setSearch] = useState(new URL(location.href).searchParams.get('q') ?? '')

	const handleSearch = () => {
		const searchParams = new URLSearchParams()
		console.log(regions)
		if (regions.length > 0) searchParams.set('region', regions.join(','))
		if (search) searchParams.set('q', search);
		router.visit('/companies?' + searchParams.toString(), {
			only: ['companies'],
			preserveState: true
		})
	}
	return (
		<>
			<div className="flex items-center gap-5 mb-5">
				<Input type="text" role="search" value={search} placeholder="Search..." className="w-52" onChange={e => setSearch(e.currentTarget.value)} />
				<ComboBox value={regions} onChange={setRegions} items={_regions.map(region => ({ label: region, value: region }))} />
				<Button onClick={handleSearch}>Search</Button>
			</div>
			<div className="flex-1 space-y-5">
				{Array.from(companies.data.values()).map(company => (
					<CompanyPreview company={company} key={company.id} />
				))}
			</div>
			<Paginator paginator={companies} />
		</>
	)
}
