// resources/js/Pages/companies/Show.tsx
import React from "react"
import { Card, CardFooter, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card'
import type {Company, Job, Pagination} from '@/lib/types'
import {EnvelopeIcon, GlobeAltIcon, MapPinIcon, PhoneIcon} from "@heroicons/react/24/outline";
import {Button} from "@/components/ui/button";
import JobPreview from "@/components/JobPreview";
import Paginator from "@/components/Paginator";

interface Props {
	company: Company,
	jobs: Pagination<Job>
}

export default function Show({ company, jobs }: Props) {
	return (
		<>
			<Card>
				<CardHeader className="flex-row gap-3">
					<img src={company.logo} alt={company.name} className="inline-block h-20 w-20" />
					<div className="flex-1">
						<div className="flex items-center justify-between">
							<CardTitle className="">{company.name}</CardTitle>
							<div className="flex items-center gap-1">
								<MapPinIcon className="w-5 h-5" />
								<span>{company.location}</span>
							</div>
						</div>
						<div className="flex items-center gap-10 mt-1">
							<Button variant="link" className="flex items-center gap-2 p-0">
								<GlobeAltIcon className="inline-block w-5 h-5" />
								<span>{company.website}</span>
							</Button>
							<Button variant="link" className="flex items-center gap-2 p-0">
								<EnvelopeIcon className="inline-block w-5 h-5" />
								<span>{company.email}</span>
							</Button>
							<Button variant="link" className="flex items-center gap-2 p-0">
								<PhoneIcon className="inline-block w-5 h-5" />
								<span>{company.phone}</span>
							</Button>
						</div>
					</div>
				</CardHeader>
				<CardContent>
					<CardDescription>{company.description}</CardDescription>
				</CardContent>
			</Card>
			<div className="mt-10">
				<span className="block text-lg font-medium mb-5">There {jobs.total === 1 ? 'is 1 job': `are ${jobs.total} jobs`} available</span>
				<div className="space-y-5">
					{jobs.data.map(job => (
						<JobPreview job={job} key={job.id} />
					))}
				</div>
				<Paginator paginator={jobs} />
			</div>
		</>

	)
}

// resources/js/Pages/companies/Show.vue
<script lang="ts" setup>
import AppLayout from "@/layouts/AppLayout.vue";
import type {Company, Job, Pagination} from "@/utils/types";
import JobPreview from "@/components/JobPreview.vue";
import Paginator from "@/components/Paginator.vue"

const props = defineProps<{
	company: Company, jobs: Pagination<Job>
}>();

defineOptions({layout: AppLayout})

</script>

<template>
	<Card :pt="{ title: { class: 'flex items-start gap-5' }}">
		<template #title>
			<img :alt="company.name" :src="company.logo" class="inline-block w-20 h-20"/>
			<div class="flex-1 ">
				<div class="flex items-center justify-between">
					<span>{{ company.name }}</span>
					<div class="flex items-center gap-2">
						<i class="pi pi-map-marker"></i>
						<span class="font-normal text-base">{{ company.location }}</span>
					</div>
				</div>
				<div class="flex items-center gap-12 mt-2">
					<a :href="company.website"
					   class="flex items-center gap-2 hover:text-blue-500"
					   target="_blank">
						<i class="pi pi-globe"></i>
						<span class="text-base">Website</span>
					</a>
					<a :href="'mailto:' + company.email"
					   class="flex items-center gap-2 hover:text-blue-500">
						<i class="pi pi-envelope"></i>
						<span class="text-base">Email</span>
					</a>
					<a :href="'tel:' + company.phone"
					   class="flex items-center gap-2 hover:text-blue-500">
						<i class="pi pi-phone"></i>
						<span class="text-base">Phone</span>
					</a>
				</div>
			</div>
		</template>
		<template #content>
			{{ company.description }}
		</template>
	</Card>

	<div class="mt-16 flex-1">
		<span class="font-medium text-xl">There are {{ jobs.data.length }} jobs available!</span>

		<div class="space-y-12 mt-5">
			<JobPreview v-for="job in jobs.data" :job="job"/>
		</div>
	</div>
	<Paginator :paginator="jobs"/>
</template>
