// resources/js/Pages/auth/Login.tsx
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {Link, useForm} from "@inertiajs/react";
import {FormEvent} from "react";
import route from "ziggy-js";
import FormField from "@/components/FormField";
import {KeyTypeSelector, Company} from "@/lib/types";

type Login = {
	email: string,
	password: string,
	remember: boolean
}

export default function Login() {
	const form = useForm<Login>({
		email: '',
		password: '',
		remember: false
	})

	function setData<K extends keyof Login>(name: K, value: KeyTypeSelector<Login, K>) {
		form.setData(name, value);
		if (form.errors[name]) form.clearErrors(name);
	}

	function handleSubmit(e: FormEvent<HTMLFormElement>) {
		e.preventDefault();
		form.post('/auth/login');
	}

	return (
		<>
			<div className="space-y-6 w-80">
				<div className="space-y-2 text-center">
					<h1 className="text-2xl font-semibold tracking-tight">Login</h1>
					<p className="text-sm text-muted-foreground">Enter your credentials to enter your account</p>
				</div>
				<form onSubmit={handleSubmit} className="space-y-4">
					<FormField name="Email" onChange={e => setData('email', e.currentTarget.value)} error={form.errors.email}/>
					<FormField name="Password" onChange={e => setData('password', e.currentTarget.value)} error={form.errors.password}/>
					<div className="flex items-center gap-2">
						<Checkbox id="remember" checked={form.data.remember} onCheckedChange={e => form.setData('remember', e as boolean)} />
						<Label className="text-sm font-normal" htmlFor="remember">Remember me</Label>
					</div>
					<Button type="submit" dusk="submit" className="w-full">Login</Button>
				</form>
			</div>
			<Button variant="ghost" asChild className="absolute top-10 right-10">
				<Link href={route('auth.register')}>
					Register
				</Link>
			</Button>
		</>
	)
}

// resources/js/Pages/auth/Login.vue
<script setup lang="ts">
import AuthLayout from "@/layouts/AuthLayout.vue";
import { useForm } from "@inertiajs/vue3";
import FormInput from "@/components/FormInput.vue";
import route from "ziggy-js";

defineOptions({ layout: AuthLayout })

let form = useForm({
	email: null,
	password: null,
});

function handleSubmit() {
	form.post("/auth/login", {
		onError(errors) {
			if (errors.email === "Invalid Credentials") {
				form.reset("password");
			}
			setTimeout(() => form.clearErrors(...Object.keys(errors)), 3000);
		},
	});
}
</script>

<template>
	<form class="w-96 flex flex-col gap-5" @submit.prevent="handleSubmit">
		<h1 class="text-2xl font-semibold text-center">Login</h1>

		<FormInput name="Email" v-model:value="form.email" :error="form.errors.email"/>
		<FormInput name="Password" v-model:value="form.password" :error="form.errors.password" type="password" />

		<button
			class="w-full px-3 py-1.5 text-white font-medium bg-cyan-400 hover:bg-cyan-500 rounded-md active:scale-[98%] transition-transform"
			type="submit"
		>
			Login
		</button>

		<p class="text-sm mt-3 text-center text-gray-800">
			Not logged in yet?
			<a
				class="font-medium text-sky-500 hover:underline"
                :href="route('auth.register')"
			>
				Register instead!
			</a>
		</p>
	</form>
</template>
